#链接谷歌云盘和Colab

In [1]:
!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse
from google.colab import auth
auth.authenticate_user()
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}

E: Package 'python-software-properties' has no installation candidate
Selecting previously unselected package google-drive-ocamlfuse.
(Reading database ... 131289 files and directories currently installed.)
Preparing to unpack .../google-drive-ocamlfuse_0.7.6-0ubuntu1~ubuntu18.04.1_amd64.deb ...
Unpacking google-drive-ocamlfuse (0.7.6-0ubuntu1~ubuntu18.04.1) ...
Setting up google-drive-ocamlfuse (0.7.6-0ubuntu1~ubuntu18.04.1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=32555940559.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force
··········
Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=32555940559.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=ht

#查看当前路径

In [2]:
!mkdir -p drive
!google-drive-ocamlfuse -o nonempty drive
import os
os.chdir("drive")
!ls

aclImdb_v1.tar.gz     residual_plot.png      Titanic
data_description.txt  Sales		     torchtest.ipynb
drive		      sample_submission.csv  train.csv
GuodongDrive	      Sense1.ipynb	     Untitled0.ipynb
House		      Sense2.ipynb（副本）   XGboost_practice1.ipynb
Houseprice.ipynb      Sense.ipynb	     XGboost_practice2.ipynb
huawei		      sensePY.ipynb	     剑指offer
labeledTrainData.tsv  submission.csv	     数组和链表.desktop
neg		      test.csv		     糖尿病数据.txt
practice	      testData.tsv


In [3]:
os.chdir("practice")
os.chdir("ch7")
!ls

air_data.csv  zscoredata.xls   航空公司客户价值分析.ipynb
ch_en.xls     zscoreddata.xls


#开始

programmer_1-->关于原始数据的一些特征描述并
保存为新表，使用describe函数

programmer_2-->对原始数据进行清理，对其中某
些数据做运算，并进行保存

programmer_3-->标准化数据并进行保存

programmer_4-->使用KMeans对数据进行聚类分析

In [0]:
import pandas as pd
from sklearn.cluster import KMeans

In [8]:
data = pd.read_csv('air_data.csv',encoding = 'utf-8')
# 包括对数据的基本描述，percentiles参数是指定计算多少的分位数表（如1/4分位数、中位数等）；
#T是转置，转置后更方便查阅
explore = data.describe(percentiles = [],include = 'all').T
#describe函数自动计算非空值数，需手动计算空值数
explore['null'] = len(data) - explore['count']
explore = explore[['null','max','min']]
explore.columns = [u'空值数',u'最大值',u'最小值']
#explore = explore.drop('MEMBER_NO')
explore.head()

空值数    最大值  最小值
MEMBER_NO           0  62988    1
FFP_DATE            0    NaN  NaN
FIRST_FLIGHT_DATE   0    NaN  NaN
GENDER              3    NaN  NaN
FFP_TIER            0      6    4

In [10]:
# 使用乘法运算非空数值的数据，因为numpy不支持*运算，在这里换做&运算
data = data[data['SUM_YR_1'].notnull() & data['SUM_YR_2'].notnull()]
# 只保留票价非零的，或者平均折扣率与总飞行公里数同时为0的记录。
index1 = data['SUM_YR_1'] != 0
index2 = data['SUM_YR_2'] != 0
index3 = (data['SEG_KM_SUM'] == 0) & (data['avg_discount'] == 0) # 该规则是“与”
data = data[index1 | index2 | index3]  # 该规则是“或”
data.head()

MEMBER_NO    FFP_DATE  ... Ration_L1Y_BPS Point_NotFlight
0      54993  2006/11/02  ...       0.512777              50
1      28065  2007/02/19  ...       0.510708              33
2      55106  2007/02/01  ...       0.518530              26
3      21189  2008/08/22  ...       0.448275              12
4      39546  2009/04/10  ...       0.530943              39

[5 rows x 44 columns]

In [18]:
data = pd.read_excel('zscoredata.xls')
data = (data- data.mean(axis = 0))/(data.std(axis = 0))
data.columns = ['Z' + i for i in data.columns]
data.head()

ZL        ZR        ZF        ZM        ZC
0  1.689882  0.140299 -0.635788  0.068794 -0.337186
1  1.689882 -0.322442  0.852453  0.843848 -0.553613
2  1.681743 -0.487707 -0.210576  0.158569 -1.094680
3  1.534185 -0.785184  0.002030  0.273091 -1.148787
4  0.890167 -0.426559 -0.635788 -0.685170  1.231909

In [0]:
data.to_excel('processed_zscoredata.xls', index=False)


In [0]:
data = pd.read_excel('processed_zscoredata.xls')

In [24]:
  k = 5
  kmodel = KMeans(n_clusters=k, n_jobs=3)
  kmodel.fit(data)

  print(kmodel.cluster_centers_)  # 查看聚类中心
  print(kmodel.labels_)  # 查看各样本对应的类别

[[ 0.48347647 -0.79941777  2.48236495  2.42356419  0.30943042]
 [-0.70078618 -0.41511584 -0.16075614 -0.16047844 -0.25672933]
 [ 0.05149901 -0.00271409 -0.23091725 -0.23512403  2.1772287 ]
 [ 1.16037972 -0.37741377 -0.08700996 -0.09501774 -0.15844696]
 [-0.31405921  1.68670155 -0.57387501 -0.53664509 -0.17239155]]
[3 3 3 ... 3 3 3]
